import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding database...')

  // Create default owner
  const ownerPin = await bcrypt.hash('1234', 10)
  const employeePin = await bcrypt.hash('0000', 10)

  await prisma.user.upsert({
    where: { id: 'owner-1' },
    update: {},
    create: { id: 'owner-1', name: 'Dueño', pin: ownerPin, role: 'OWNER' },
  })
  await prisma.user.upsert({
    where: { id: 'emp-1' },
    update: {},
    create: { id: 'emp-1', name: 'Empleado', pin: employeePin, role: 'EMPLOYEE' },
  })

  const products = [
    // ── CARNES PREPARADAS ──
    { name: 'Pulled Pork',            category: 'Carnes', module: 'CARNES_PREPARADAS', unit: 'LB',    minStock: 5  },
    { name: 'Costillas',              category: 'Carnes', module: 'CARNES_PREPARADAS', unit: 'LB',    minStock: 5  },
    { name: 'Pork Belly',             category: 'Carnes', module: 'CARNES_PREPARADAS', unit: 'LB',    minStock: 5  },
    { name: 'Brisket',                category: 'Carnes', module: 'CARNES_PREPARADAS', unit: 'LB',    minStock: 5  },
    { name: 'Pollo',                  category: 'Carnes', module: 'CARNES_PREPARADAS', unit: 'LB',    minStock: 5  },
    { name: 'Tortitas para Hamburguesa', category: 'Carnes', module: 'CARNES_PREPARADAS', unit: 'unidad', minStock: 10 },
    { name: 'Texas Twinkies',         category: 'Carnes', module: 'CARNES_PREPARADAS', unit: 'unidad', minStock: 8  },
    { name: 'Puyaso',                 category: 'Carnes', module: 'CARNES_PREPARADAS', unit: 'LB',    minStock: 3  },

    // ── CARNES AHUMADAS ──
    { name: 'Costilla de Cerdo',      category: 'Ahumadas', module: 'CARNES_AHUMADAS', unit: 'LB', minStock: 20 },
    { name: 'Brisket',                category: 'Ahumadas', module: 'CARNES_AHUMADAS', unit: 'LB', minStock: 10 },
    { name: 'Pork Belly',             category: 'Ahumadas', module: 'CARNES_AHUMADAS', unit: 'LB', minStock: 20 },
    { name: 'Pulled Pork',            category: 'Ahumadas', module: 'CARNES_AHUMADAS', unit: 'LB', minStock: 30 },
    { name: 'Puyaso',                 category: 'Ahumadas', module: 'CARNES_AHUMADAS', unit: 'LB', minStock: 5  },
    { name: 'Muslos de Pollo',        category: 'Ahumadas', module: 'CARNES_AHUMADAS', unit: 'unidad', minStock: 15 },
    { name: 'Tortitas de Carne',      category: 'Ahumadas', module: 'CARNES_AHUMADAS', unit: 'unidad', minStock: 10 },
    { name: 'Texas Twinkies',         category: 'Ahumadas', module: 'CARNES_AHUMADAS', unit: 'unidad', minStock: 8  },

    // ── CARNE CRUDA ──
    { name: 'Costilla de Cerdo',      category: 'Carne Cruda', module: 'CARNE_CRUDA', unit: 'LB', minStock: 0 },
    { name: 'Brisket',                category: 'Carne Cruda', module: 'CARNE_CRUDA', unit: 'LB', minStock: 0 },
    { name: 'Panceta',                category: 'Carne Cruda', module: 'CARNE_CRUDA', unit: 'LB', minStock: 0 },
    { name: 'Nuca de Cerdo',          category: 'Carne Cruda', module: 'CARNE_CRUDA', unit: 'LB', minStock: 0 },
    { name: 'Puyaso',                 category: 'Carne Cruda', module: 'CARNE_CRUDA', unit: 'LB', minStock: 0 },
    { name: 'Muslos de Pollo',        category: 'Carne Cruda', module: 'CARNE_CRUDA', unit: 'LB', minStock: 0 },
    { name: 'Carne Molida',           category: 'Carne Cruda', module: 'CARNE_CRUDA', unit: 'LB', minStock: 0 },
    { name: 'Carne para moler',       category: 'Carne Cruda', module: 'CARNE_CRUDA', unit: 'LB', minStock: 0 },

    // ── VERDURAS ──
    { name: 'Papa',                   category: 'Verduras', module: 'VERDURAS', unit: 'LB', minStock: 5  },
    { name: 'Zanahoria',              category: 'Verduras', module: 'VERDURAS', unit: 'LB', minStock: 3  },
    { name: 'Repollo Blanco',         category: 'Verduras', module: 'VERDURAS', unit: 'LB', minStock: 5  },
    { name: 'Repollo Morado',         category: 'Verduras', module: 'VERDURAS', unit: 'LB', minStock: 3  },
    { name: 'Camote',                 category: 'Verduras', module: 'VERDURAS', unit: 'LB', minStock: 5  },
    { name: 'Cebollin',               category: 'Verduras', module: 'VERDURAS', unit: 'LB', minStock: 1  },
    { name: 'Arugula',                category: 'Verduras', module: 'VERDURAS', unit: 'LB', minStock: 1  },
    { name: 'Limones',                category: 'Verduras', module: 'VERDURAS', unit: 'LB', minStock: 5  },
    { name: 'Cebolla Morada',         category: 'Verduras', module: 'VERDURAS', unit: 'LB', minStock: 2  },
    { name: 'Cebolla Blanca',         category: 'Verduras', module: 'VERDURAS', unit: 'LB', minStock: 3  },
    { name: 'Jalapeño',               category: 'Verduras', module: 'VERDURAS', unit: 'LB', minStock: 1  },

    // ── BEBIDAS BODEGA ──
    { name: 'Coca-Cola vidrio',       category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 48 },
    { name: 'Coca-Cola zero vidrio',  category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 48 },
    { name: 'Coca cola lata',         category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Coca cola zero lata',    category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Tropical uva',           category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Tropical fresa',         category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Pepsi black',            category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 12 },
    { name: 'Pepsi',                  category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 12 },
    { name: 'Kolashampan',            category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Salutari de limón',      category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Salutari de naranja',    category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Salutari de toronja',    category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Agua mineral',           category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Te limón',               category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Te de frambuesa',        category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Te de durazno',          category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Botella con agua',       category: 'Refrescos', module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Regia chola 750ml',      category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Regia paq 355',          category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Regia lata',             category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Ultra',                  category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 12 },
    { name: 'Suprema',                category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 12 },
    { name: 'Pilsener',               category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 24 },
    { name: 'Pilsener lata',          category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 12 },
    { name: 'Estrella Damm',          category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 6  },
    { name: 'Corona',                 category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 12 },
    { name: 'Corona Zero',            category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 6  },
    { name: 'Modelo',                 category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 6  },
    { name: 'Cadejo Negra',           category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 12 },
    { name: 'Cadejo hija de pooh',    category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 12 },
    { name: 'Cadejo mera belga',      category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 12 },
    { name: 'Heineken 0',             category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 6  },
    { name: 'Stella Artois',          category: 'Cervezas',  module: 'BEBIDAS_BODEGA', unit: 'unidad', minStock: 6  },

    // ── BEBIDAS SERVICIO ──
    { name: 'Coca-Cola vidrio',       category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 10 },
    { name: 'Coca-Cola zero vidrio',  category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 10 },
    { name: 'Coca cola lata',         category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 10 },
    { name: 'Coca cola zero lata',    category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 10 },
    { name: 'Sprite',                 category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 10 },
    { name: 'Tropical uva',           category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Pepsi black',            category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Pepsi',                  category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Kolashampan',            category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Salutari de limón',      category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Salutari de naranja',    category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Salutari de toronja',    category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Agua mineral',           category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Te limón',               category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Te de frambuesa',        category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Te de durazno',          category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Botella con agua',       category: 'Refrescos', module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Regia chola 750ml',      category: 'Cervezas',  module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Regia paq 355',          category: 'Cervezas',  module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Regia lata',             category: 'Cervezas',  module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Ultra',                  category: 'Cervezas',  module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 3  },
    { name: 'Suprema',                category: 'Cervezas',  module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 5  },
    { name: 'Corona',                 category: 'Cervezas',  module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 3  },
    { name: 'Heineken 0',             category: 'Cervezas',  module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 3  },
    { name: 'Stella Artois',          category: 'Cervezas',  module: 'BEBIDAS_SERVICIO', unit: 'unidad', minStock: 3  },

    // ── SALSAS ──
    { name: 'Higos',                  category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 5    },
    { name: 'Cerveza',                category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 4.5  },
    { name: 'Tamarindo',              category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 0    },
    { name: 'Panela',                 category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 5    },
    { name: 'Cilantro',               category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 4    },
    { name: 'Chipotle',               category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 4    },
    { name: 'Pulpa tamarindo',        category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 0    },
    { name: 'Maracuya',               category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 10   },
    { name: 'Romero',                 category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 1    },
    { name: 'Blue Cheese',            category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 1    },
    { name: 'White BBQ',              category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 1    },
    { name: 'Sabor a queso',          category: 'Salsas', module: 'SALSAS', unit: 'unidad', minStock: 1    },

    // ── COCINA ──
    { name: 'Tortitas Hamburguesa',   category: 'Carnes',       module: 'COCINA', unit: 'unidad', minStock: 0   },
    { name: 'Tocino',                 category: 'Carnes',       module: 'COCINA', unit: 'LB',     minStock: 1   },
    { name: 'Texas Twinkies',         category: 'Entrada',      module: 'COCINA', unit: 'unidad', minStock: 8   },
    { name: 'Papas Fritas',           category: 'Guarniciones', module: 'COCINA', unit: 'bolsa',  minStock: 1   },
    { name: 'Mac and Cheese',         category: 'Guarniciones', module: 'COCINA', unit: 'unidad', minStock: 1   },
    { name: 'Cream Corn',             category: 'Guarniciones', module: 'COCINA', unit: 'unidad', minStock: 1   },
    { name: 'Ensalada de Papa',       category: 'Guarniciones', module: 'COCINA', unit: 'unidad', minStock: 1   },
    { name: 'Sal',                    category: 'Condimentos',  module: 'COCINA', unit: 'LB',     minStock: 0   },
    { name: 'Pimienta',               category: 'Condimentos',  module: 'COCINA', unit: 'unidad', minStock: 0   },
    { name: 'Sazonador papas',        category: 'Condimentos',  module: 'COCINA', unit: 'unidad', minStock: 0   },
    { name: 'Pan de pretzel',         category: 'Panes',        module: 'COCINA', unit: 'unidad', minStock: 6   },
    { name: 'Pan de Papa',            category: 'Panes',        module: 'COCINA', unit: 'unidad', minStock: 6   },
    { name: 'Maracuya',               category: 'Extractos',    module: 'COCINA', unit: 'unidad', minStock: 1   },
    { name: 'Arugula',                category: 'Verduras',     module: 'COCINA', unit: 'caja',   minStock: 1   },
    { name: 'Cebolla',                category: 'Verduras',     module: 'COCINA', unit: 'LB',     minStock: 0   },
    { name: 'Cebolla morada',         category: 'Verduras',     module: 'COCINA', unit: 'LB',     minStock: 0   },
    { name: 'Limon',                  category: 'Verduras',     module: 'COCINA', unit: 'unidad', minStock: 0   },
    { name: 'Cebollines',             category: 'Verduras',     module: 'COCINA', unit: 'manojo', minStock: 0   },
    { name: 'Zanahoria',              category: 'Verduras',     module: 'COCINA', unit: 'LB',     minStock: 0   },
    { name: 'Elotito amarillo',       category: 'Verduras',     module: 'COCINA', unit: 'unidad', minStock: 0   },
    { name: 'Repollo Blanco',         category: 'Verduras',     module: 'COCINA', unit: 'LB',     minStock: 0.2 },
    { name: 'Repollo Morado',         category: 'Verduras',     module: 'COCINA', unit: 'LB',     minStock: 0   },
    { name: 'Camote',                 category: 'Verduras',     module: 'COCINA', unit: 'LB',     minStock: 0   },
    { name: 'Coditos',                category: 'Harinas',      module: 'COCINA', unit: 'LB',     minStock: 2   },
    { name: 'Queso Crema',            category: 'Lacteos',      module: 'COCINA', unit: 'unidad', minStock: 0   },
    { name: 'Yogurt',                 category: 'Lacteos',      module: 'COCINA', unit: 'unidad', minStock: 1   },
    { name: 'Queso Americano',        category: 'Lacteos',      module: 'COCINA', unit: 'unidad', minStock: 0   },
    { name: 'Mayonesa',               category: 'Lacteos',      module: 'COCINA', unit: 'unidad', minStock: 0   },
    { name: 'Mix de queso',           category: 'Lacteos',      module: 'COCINA', unit: 'LB',     minStock: 1   },
    { name: 'Leche',                  category: 'Lacteos',      module: 'COCINA', unit: 'unidad', minStock: 1   },
    { name: 'Crema',                  category: 'Lacteos',      module: 'COCINA', unit: 'unidad', minStock: 1   },
    { name: 'Azucar',                 category: 'Varios',       module: 'COCINA', unit: 'unidad', minStock: 0   },
    { name: 'Mostaza Dijon',          category: 'Varios',       module: 'COCINA', unit: 'unidad', minStock: 0   },
    { name: 'Guantes Negros',         category: 'Varios',       module: 'COCINA', unit: 'caja',   minStock: 0   },
    { name: 'Guantes Transparentes',  category: 'Varios',       module: 'COCINA', unit: 'caja',   minStock: 0   },
    { name: 'Papel toalla cocina',    category: 'Varios',       module: 'COCINA', unit: 'rollo',  minStock: 0   },
    { name: 'Aceite y Margarinas',    category: 'Aceite',       module: 'COCINA', unit: 'bidon',  minStock: 1   },

    // ── SERVICIO ──
    { name: 'Bolsa #1',               category: 'Bolsas',  module: 'SERVICIO', unit: 'paquete', minStock: 0   },
    { name: 'Bolsa #2',               category: 'Bolsas',  module: 'SERVICIO', unit: 'paquete', minStock: 0   },
    { name: 'Bolsa #3',               category: 'Bolsas',  module: 'SERVICIO', unit: 'paquete', minStock: 0   },
    { name: 'Bolsa Jardinera 34x50',  category: 'Bolsas',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Bolsa Higienica 19x27',  category: 'Bolsas',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Bolsa Medio Jardin 24x32', category: 'Bolsas', module: 'SERVICIO', unit: 'unidad', minStock: 0   },
    { name: 'Ziploc',                 category: 'Bolsas',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Bolsa 8x12',             category: 'Bolsas',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Papel Higienico',        category: 'Varios',  module: 'SERVICIO', unit: 'paquete', minStock: 0   },
    { name: 'Papel toalla baño',      category: 'Varios',  module: 'SERVICIO', unit: 'paquete', minStock: 0   },
    { name: 'Servilleta Servilletero', category: 'Varios', module: 'SERVICIO', unit: 'paquete', minStock: 0   },
    { name: 'Servilleta Normal',      category: 'Varios',  module: 'SERVICIO', unit: 'paquete', minStock: 0   },
    { name: 'Papel Aluminio',         category: 'Varios',  module: 'SERVICIO', unit: 'rollo',   minStock: 0   },
    { name: 'Bandeja de llevar',      category: 'Varios',  module: 'SERVICIO', unit: 'unidad',  minStock: 50  },
    { name: 'Bandeja #8 papas',       category: 'Varios',  module: 'SERVICIO', unit: 'paquete', minStock: 0   },
    { name: 'Cubiertos para llevar',  category: 'Varios',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Cucharitas',             category: 'Varios',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Tenedores pequeños',     category: 'Varios',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Vasos #16',              category: 'Varios',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Cup 2 Onz',              category: 'Varios',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Tapa de 2oz',            category: 'Varios',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Funda de Cubiertos',     category: 'Varios',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Stickers',               category: 'Varios',  module: 'SERVICIO', unit: 'rollo',   minStock: 0   },
    { name: 'Pajillas',               category: 'Varios',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Papelito de post',       category: 'Varios',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Tirro Scotch',           category: 'Varios',  module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Salsa Inglesa',          category: 'Bebidas', module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Chamoy',                 category: 'Bebidas', module: 'SERVICIO', unit: 'unidad',  minStock: 0   },
    { name: 'Tajin',                  category: 'Bebidas', module: 'SERVICIO', unit: 'unidad',  minStock: 0   },

    // ── BODEGA ──
    { name: 'Mayonesa',               category: 'Salsas',     module: 'BODEGA', unit: 'unidad',  minStock: 2  },
    { name: 'Azucar',                 category: 'Varios',     module: 'BODEGA', unit: 'unidad',  minStock: 3  },
    { name: 'Ketchup',                category: 'Salsas',     module: 'BODEGA', unit: 'unidad',  minStock: 3  },
    { name: 'Mostaza de Grano',       category: 'Salsas',     module: 'BODEGA', unit: 'unidad',  minStock: 5  },
    { name: 'BBQ',                    category: 'Salsas',     module: 'BODEGA', unit: 'unidad',  minStock: 3  },
    { name: 'Miel',                   category: 'Varios',     module: 'BODEGA', unit: 'galón',   minStock: 1  },
    { name: 'Papel aluminio',         category: 'Varios',     module: 'BODEGA', unit: 'rollo',   minStock: 2  },
    { name: 'Panela',                 category: 'Varios',     module: 'BODEGA', unit: 'unidad',  minStock: 6  },
    { name: 'Margarina',              category: 'Varios',     module: 'BODEGA', unit: 'unidad',  minStock: 10 },
    { name: 'Bicarbonato',            category: 'Varios',     module: 'BODEGA', unit: 'unidad',  minStock: 5  },
    { name: 'Vita Sal',               category: 'Varios',     module: 'BODEGA', unit: 'unidad',  minStock: 24 },
    { name: 'Lata Melocoton',         category: 'Latas',      module: 'BODEGA', unit: 'unidad',  minStock: 1  },
    { name: 'Lata Maiz Dulces',       category: 'Latas',      module: 'BODEGA', unit: 'unidad',  minStock: 5  },
    { name: 'Lata Higo',              category: 'Latas',      module: 'BODEGA', unit: 'unidad',  minStock: 3  },
    { name: 'Pimienta',               category: 'Especias',   module: 'BODEGA', unit: 'bote',    minStock: 3  },
    { name: 'Cebolla Granulada',      category: 'Especias',   module: 'BODEGA', unit: 'bote',    minStock: 3  },
    { name: 'Ajo granulado',          category: 'Especias',   module: 'BODEGA', unit: 'bote',    minStock: 3  },
    { name: 'Sazonador Italiano',     category: 'Especias',   module: 'BODEGA', unit: 'bote',    minStock: 3  },
    { name: 'Rostisserie Chicken',    category: 'Especias',   module: 'BODEGA', unit: 'bote',    minStock: 3  },
    { name: 'Paprika',                category: 'Especias',   module: 'BODEGA', unit: 'bote',    minStock: 3  },
    { name: 'Sazon Completo',         category: 'Especias',   module: 'BODEGA', unit: 'bote',    minStock: 2  },
    { name: 'Row',                    category: 'Especias',   module: 'BODEGA', unit: 'bote',    minStock: 8  },
    { name: 'Canela Raja',            category: 'Especias',   module: 'BODEGA', unit: 'unidad',  minStock: 1  },
    { name: 'Chile Waco',             category: 'Especias',   module: 'BODEGA', unit: 'bolsa',   minStock: 1  },
    { name: 'Clavo olor',             category: 'Especias',   module: 'BODEGA', unit: 'bolsa',   minStock: 1  },
    { name: 'Tomillo',                category: 'Especias',   module: 'BODEGA', unit: 'bolsa',   minStock: 0  },
    { name: 'Achote',                 category: 'Especias',   module: 'BODEGA', unit: 'bolsa',   minStock: 0  },
    { name: 'Chile Morron',           category: 'Especias',   module: 'BODEGA', unit: 'unidad',  minStock: 1  },
    { name: 'Sal Parrillera',         category: 'Especias',   module: 'BODEGA', unit: 'bolsa',   minStock: 10 },
    { name: 'Pimienta Gorda',         category: 'Especias',   module: 'BODEGA', unit: 'bolsa',   minStock: 1  },
    { name: 'Oregano',                category: 'Especias',   module: 'BODEGA', unit: 'bolsa',   minStock: 0  },
    { name: 'Ajonjoli',               category: 'Especias',   module: 'BODEGA', unit: 'bolsa',   minStock: 0  },
    { name: 'Flor Jamaica',           category: 'Especias',   module: 'BODEGA', unit: 'bolsa',   minStock: 0  },
    { name: 'Vinagre Manzana',        category: 'Líquidos',   module: 'BODEGA', unit: 'galón',   minStock: 1  },
    { name: 'Soya',                   category: 'Líquidos',   module: 'BODEGA', unit: 'galón',   minStock: 1  },
    { name: 'Vinagre Blanco',         category: 'Líquidos',   module: 'BODEGA', unit: 'galón',   minStock: 1  },
    { name: 'Salsa Inglesa',          category: 'Líquidos',   module: 'BODEGA', unit: 'galón',   minStock: 2  },
    { name: 'Papel Higienico',        category: 'Higiene',    module: 'BODEGA', unit: 'paquete', minStock: 12 },
    { name: 'Palillos',               category: 'Higiene',    module: 'BODEGA', unit: 'bote',    minStock: 5  },
    { name: 'Guante L',               category: 'Higiene',    module: 'BODEGA', unit: 'caja',    minStock: 0  },
    { name: 'Guante M',               category: 'Higiene',    module: 'BODEGA', unit: 'caja',    minStock: 0  },
    { name: 'Servilleta de baño',     category: 'Higiene',    module: 'BODEGA', unit: 'unidad',  minStock: 8  },
    { name: 'Servilleta cuadrada',    category: 'Higiene',    module: 'BODEGA', unit: 'unidad',  minStock: 10 },
    { name: 'Servilleta interfoliada', category: 'Higiene',   module: 'BODEGA', unit: 'unidad',  minStock: 48 },
    { name: 'Red de Ajos',            category: 'Varios',     module: 'BODEGA', unit: 'unidad',  minStock: 15 },
    { name: 'Ziploct',                category: 'Varios',     module: 'BODEGA', unit: 'caja',    minStock: 2  },
    { name: 'Desengrasante',          category: 'Limpieza',   module: 'BODEGA', unit: 'unidad',  minStock: 2  },
    { name: 'Leche',                  category: 'Lacteos',    module: 'BODEGA', unit: 'unidad',  minStock: 6  },
    { name: 'Tajin',                  category: 'Varios',     module: 'BODEGA', unit: 'unidad',  minStock: 3  },
    { name: 'Chamoy',                 category: 'Varios',     module: 'BODEGA', unit: 'unidad',  minStock: 3  },
    { name: 'Crema',                  category: 'Lacteos',    module: 'BODEGA', unit: 'unidad',  minStock: 10 },
    { name: 'Mostacilla',             category: 'Especias',   module: 'BODEGA', unit: 'libra',   minStock: 1  },

    // ── DESECHABLES ──
    { name: 'Bolsa #1',               category: 'Bolsas',     module: 'DESECHABLES', unit: 'unidad',  minStock: 100  },
    { name: 'Bolsa #2',               category: 'Bolsas',     module: 'DESECHABLES', unit: 'unidad',  minStock: 100  },
    { name: 'Bolsa #3',               category: 'Bolsas',     module: 'DESECHABLES', unit: 'unidad',  minStock: 100  },
    { name: 'Bolsa 8x12',             category: 'Bolsas',     module: 'DESECHABLES', unit: 'unidad',  minStock: 100  },
    { name: 'Bolsa Higienica Blanca', category: 'Bolsas',     module: 'DESECHABLES', unit: 'unidad',  minStock: 50   },
    { name: 'Bolsa Medio Jardin 24x32', category: 'Bolsas',   module: 'DESECHABLES', unit: 'unidad',  minStock: 50   },
    { name: 'Bolsa Jardinera 34x50',  category: 'Bolsas',     module: 'DESECHABLES', unit: 'unidad',  minStock: 50   },
    { name: 'Ziploc',                 category: 'Bolsas',     module: 'DESECHABLES', unit: 'unidad',  minStock: 6    },
    { name: 'Papel Toalla',           category: 'Varios',     module: 'DESECHABLES', unit: 'rollo',   minStock: 6    },
    { name: 'Manteles Encerados',     category: 'Varios',     module: 'DESECHABLES', unit: 'unidad',  minStock: 2000 },
    { name: 'Cobertor de cubiertos',  category: 'Varios',     module: 'DESECHABLES', unit: 'unidad',  minStock: 1000 },
    { name: 'Caja Kraft para Llevar', category: 'Varios',     module: 'DESECHABLES', unit: 'unidad',  minStock: 100  },
    { name: 'Papel de aluminio',      category: 'Varios',     module: 'DESECHABLES', unit: 'rollo',   minStock: 2    },
    { name: 'Gas',                    category: 'Varios',     module: 'DESECHABLES', unit: 'tanque',  minStock: 2    },
    { name: 'Bandeja para llevar',    category: 'Varios',     module: 'DESECHABLES', unit: 'unidad',  minStock: 300  },
    { name: 'Cups 250',               category: 'Vasos',      module: 'DESECHABLES', unit: 'unidad',  minStock: 25   },
    { name: 'Cups 500',               category: 'Vasos',      module: 'DESECHABLES', unit: 'unidad',  minStock: 25   },
    { name: 'Vaso de 16 onz',         category: 'Vasos',      module: 'DESECHABLES', unit: 'unidad',  minStock: 200  },
    { name: 'Stickers',               category: 'Varios',     module: 'DESECHABLES', unit: 'rollo',   minStock: 1    },
    { name: 'Servilleta Interfoliada baño', category: 'Varios', module: 'DESECHABLES', unit: 'unidad', minStock: 1   },
    { name: 'Servilleta Interfoliada mesa', category: 'Varios', module: 'DESECHABLES', unit: 'unidad', minStock: 5   },
    { name: 'Servilletas para llevar', category: 'Varios',    module: 'DESECHABLES', unit: 'unidad',  minStock: 1    },
    { name: 'Guantes talla L',        category: 'Higiene',    module: 'DESECHABLES', unit: 'caja',    minStock: 1    },
    { name: 'Guantes talla M',        category: 'Higiene',    module: 'DESECHABLES', unit: 'caja',    minStock: 1    },
    { name: 'Guantes de ensalada',    category: 'Higiene',    module: 'DESECHABLES', unit: 'caja',    minStock: 1    },
    { name: 'Palillos de dientes',    category: 'Varios',     module: 'DESECHABLES', unit: 'bote',    minStock: 5    },
    { name: 'Pajilla',                category: 'Varios',     module: 'DESECHABLES', unit: 'unidad',  minStock: 1    },
    { name: 'Papel Higienico',        category: 'Higiene',    module: 'DESECHABLES', unit: 'paquete', minStock: 12   },
    { name: 'Papel termico para post', category: 'Varios',    module: 'DESECHABLES', unit: 'rollo',   minStock: 1    },
    { name: 'Papel termico para comandas', category: 'Varios', module: 'DESECHABLES', unit: 'rollo',  minStock: 1    },
  ]

  console.log(`Creating ${products.length} products...`)
  for (const p of products) {
    await prisma.product.create({ data: p as Parameters<typeof prisma.product.create>[0]['data'] })
  }

  console.log('✓ Seed complete!')
  console.log('\nDefault credentials:')
  console.log('  Dueño  → PIN: 1234')
  console.log('  Empleado → PIN: 0000')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
